# Generated by Django 6.0.2 on 2026-03-01 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rec_type', models.CharField(choices=[('cost', 'Cost Optimisation'), ('performance', 'Performance'), ('security', 'Security'), ('reliability', 'Reliability')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(blank=True, help_text='e.g. Instance, AutoScalingGroup, StorageBucket', max_length=60)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('estimated_saving_usd', models.DecimalField(decimal_places=2, default=0, help_text='Estimated monthly USD saving (0 for non-cost recommendations)', max_digits=10)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('action_payload', models.JSONField(default=dict, help_text='Machine-readable action details for automation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetectionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(choices=[('cpu_usage_percent', 'CPU Utilisation %'), ('memory_usage_percent', 'Memory Utilisation %'), ('disk_usage_percent', 'Disk Utilisation %'), ('network_in_bytes', 'Network In (bytes)'), ('network_out_bytes', 'Network Out (bytes)')], default='cpu_usage_percent', max_length=40)),
                ('instance_id', models.CharField(blank=True, db_index=True, help_text='Leave blank to watch all instances owned by this user', max_length=64, null=True)),
                ('lookback_minutes', models.PositiveIntegerField(default=60, help_text='Window (minutes) used to compute rolling baseline')),
                ('z_score_threshold', models.FloatField(default=2.5, help_text='How many std-devs above the rolling mean counts as anomalous')),
                ('min_sample_count', models.PositiveIntegerField(default=5, help_text='Minimum data points required before evaluation fires')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomaly Detection Rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(db_index=True, max_length=64)),
                ('metric', models.CharField(choices=[('cpu_usage_percent', 'CPU Utilisation %'), ('memory_usage_percent', 'Memory Utilisation %'), ('disk_usage_percent', 'Disk Utilisation %'), ('network_in_bytes', 'Network In (bytes)'), ('network_out_bytes', 'Network Out (bytes)')], max_length=40)),
                ('observed_value', models.FloatField()),
                ('baseline_mean', models.FloatField()),
                ('baseline_std', models.FloatField()),
                ('z_score', models.FloatField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai.anomalydetectionrule')),
            ],
            options={
                'verbose_name': 'Anomaly Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScalingPrediction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asg_id', models.CharField(db_index=True, help_text='AutoScalingGroup.asg_id this prediction targets', max_length=64)),
                ('direction', models.CharField(choices=[('scale_up', 'Scale Up'), ('scale_down', 'Scale Down'), ('maintain', 'Maintain')], max_length=12)),
                ('predicted_metric', models.CharField(choices=[('cpu_usage_percent', 'CPU Utilisation %'), ('memory_usage_percent', 'Memory Utilisation %'), ('disk_usage_percent', 'Disk Utilisation %'), ('network_in_bytes', 'Network In (bytes)'), ('network_out_bytes', 'Network Out (bytes)')], max_length=40)),
                ('predicted_value', models.FloatField(help_text='Forecasted metric value at target_time')),
                ('current_capacity', models.IntegerField(default=0)),
                ('recommended_capacity', models.IntegerField(default=0)),
                ('confidence_pct', models.FloatField(default=0.0, help_text='Model confidence score 0-100')),
                ('horizon_minutes', models.PositiveIntegerField(default=30)),
                ('target_time', models.DateTimeField(blank=True, null=True)),
                ('acted_upon', models.BooleanField(default=False, help_text='True once auto-scaler has applied this recommendation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scaling Prediction',
                'ordering': ['-created_at'],
            },
        ),
    ]
