# Generated by Django 6.0.2 on 2026-02-26 09:25

import django.db.models.deletion
import services.deployments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.deployments.models._uid_plan, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('build_steps', models.JSONField(default=list)),
                ('deploy_steps', models.JSONField(default=list)),
                ('env_vars', models.JSONField(default=dict)),
                ('secrets', models.JSONField(default=dict, help_text='Secret names only — values never stored in plan')),
                ('infra_resources', models.JSONField(default=list, help_text='List of infra resources to provision')),
                ('monitoring_rules', models.JSONField(default=list)),
                ('scaling_rules', models.JSONField(default=dict)),
                ('rollback_strategy', models.JSONField(default=dict)),
                ('ci_pipeline_def', models.JSONField(default=dict, help_text='Pipeline stages/jobs definition')),
                ('security_posture', models.JSONField(default=dict)),
                ('dockerfile', models.TextField(blank=True, default='')),
                ('k8s_manifests', models.JSONField(default=dict, help_text='{ deployment, service, ingress } YAML strings')),
                ('app_url', models.CharField(blank=True, default='', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deploy_plans',
            },
        ),
        migrations.CreateModel(
            name='DeploymentExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.deployments.models._uid_execution, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('stage', 'Staging'), ('prod', 'Production')], default='dev', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pipeline_id', models.CharField(blank=True, default='', help_text='ID in the CI/CD subsystem', max_length=100)),
                ('pipeline_run_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_resources', models.JSONField(default=list, help_text='[{type, id, name, status}] — fed into Resource Control')),
                ('log_lines', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('app_hostname', models.CharField(blank=True, default='', max_length=500)),
                ('app_url', models.CharField(blank=True, default='', max_length=500)),
                ('health_status', models.CharField(blank=True, default='unknown', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='deployments.deploymentplan')),
            ],
            options={
                'db_table': 'deploy_executions',
            },
        ),
        migrations.CreateModel(
            name='DeploymentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.deployments.models._uid_request, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('orcacloud', 'OrcaCloud Project'), ('zip', 'ZIP Upload')], max_length=20)),
                ('app_type', models.CharField(choices=[('financial', 'Financial App'), ('technology', 'Technology App'), ('ecommerce', 'E-Commerce'), ('news', 'News / Media'), ('research', 'Research / Science'), ('social', 'Social App'), ('ai', 'AI / ML App'), ('custom', 'Custom')], default='technology', max_length=20)),
                ('frontend', models.CharField(choices=[('react', 'React'), ('nextjs', 'Next.js'), ('vue', 'Vue'), ('angular', 'Angular'), ('svelte', 'Svelte'), ('flutter_web', 'Flutter Web'), ('static_html', 'Static HTML'), ('none', 'None')], default='none', max_length=40)),
                ('backend', models.CharField(choices=[('nodejs', 'Node.js'), ('python_django', 'Python / Django'), ('python_fastapi', 'Python / FastAPI'), ('python_flask', 'Python / Flask'), ('php_laravel', 'PHP / Laravel'), ('java_spring', 'Java / Spring Boot'), ('go', 'Go'), ('ruby_rails', 'Ruby on Rails'), ('dotnet', '.NET'), ('rust', 'Rust'), ('none', 'None')], default='none', max_length=40)),
                ('database', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('nosql', 'NoSQL'), ('sqlite', 'SQLite'), ('none', 'None')], default='none', max_length=40)),
                ('deploy_mode', models.CharField(choices=[('container', 'Container'), ('kubernetes', 'Kubernetes')], default='container', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('project_id', models.CharField(blank=True, default='', max_length=50)),
                ('new_project_name', models.CharField(blank=True, default='', help_text='Populated when user creates a new project from the wizard', max_length=200)),
                ('group_id', models.CharField(blank=True, default='', max_length=50)),
                ('git_repo', models.CharField(max_length=500)),
                ('git_branch', models.CharField(default='main', max_length=200)),
                ('target_environments', models.JSONField(default=list, help_text='e.g. ["dev","stage","prod"]')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('planned', 'Planned'), ('confirmed', 'Confirmed'), ('deploying', 'Deploying'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deploy_requests',
            },
        ),
        migrations.AddField(
            model_name='deploymentplan',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='deployments.deploymentrequest'),
        ),
        migrations.CreateModel(
            name='DeploymentAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.deployments.models._uid_audit, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text='e.g. deploy.request.created, deploy.confirmed, deploy.rollback.triggered', max_length=100)),
                ('detail', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploy_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='deployments.deploymentexecution')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='deployments.deploymentrequest')),
            ],
            options={
                'db_table': 'deploy_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.deployments.models._uid_template, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('frontend', models.CharField(choices=[('react', 'React'), ('nextjs', 'Next.js'), ('vue', 'Vue'), ('angular', 'Angular'), ('svelte', 'Svelte'), ('flutter_web', 'Flutter Web'), ('static_html', 'Static HTML'), ('none', 'None')], default='none', max_length=40)),
                ('backend', models.CharField(choices=[('nodejs', 'Node.js'), ('python_django', 'Python / Django'), ('python_fastapi', 'Python / FastAPI'), ('python_flask', 'Python / Flask'), ('php_laravel', 'PHP / Laravel'), ('java_spring', 'Java / Spring Boot'), ('go', 'Go'), ('ruby_rails', 'Ruby on Rails'), ('dotnet', '.NET'), ('rust', 'Rust'), ('none', 'None')], default='none', max_length=40)),
                ('database', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('nosql', 'NoSQL'), ('sqlite', 'SQLite'), ('none', 'None')], default='none', max_length=40)),
                ('deploy_mode', models.CharField(choices=[('container', 'Container'), ('kubernetes', 'Kubernetes')], default='container', max_length=20)),
                ('runtime_image', models.CharField(default='node:20-alpine', max_length=200)),
                ('build_commands', models.JSONField(default=list, help_text='Ordered list of shell commands for the build stage')),
                ('install_command', models.CharField(default='npm ci', max_length=500)),
                ('start_command', models.CharField(default='node server.js', max_length=500)),
                ('health_check_path', models.CharField(default='/health', max_length=200)),
                ('health_check_port', models.IntegerField(default=8000)),
                ('readiness_delay_sec', models.IntegerField(default=5)),
                ('default_replicas', models.IntegerField(default=2)),
                ('min_replicas', models.IntegerField(default=1)),
                ('max_replicas', models.IntegerField(default=10)),
                ('cpu_threshold_pct', models.IntegerField(default=65)),
                ('cpu_request', models.CharField(default='100m', max_length=20)),
                ('cpu_limit', models.CharField(default='500m', max_length=20)),
                ('memory_request', models.CharField(default='128Mi', max_length=20)),
                ('memory_limit', models.CharField(default='512Mi', max_length=20)),
                ('default_env_vars', models.JSONField(default=dict)),
                ('app_port', models.IntegerField(default=8000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'deploy_templates',
                'indexes': [models.Index(fields=['frontend', 'backend', 'database', 'deploy_mode'], name='deploy_temp_fronten_47801a_idx')],
            },
        ),
        migrations.AddField(
            model_name='deploymentrequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='deployments.deploymenttemplate'),
        ),
        migrations.AddIndex(
            model_name='deploymentexecution',
            index=models.Index(fields=['plan', 'environment'], name='deploy_exec_plan_id_44800c_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentexecution',
            index=models.Index(fields=['status', 'created_at'], name='deploy_exec_status_cffc36_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentexecution',
            index=models.Index(fields=['pipeline_id'], name='deploy_exec_pipelin_b45e36_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentauditlog',
            index=models.Index(fields=['user', 'created_at'], name='deploy_audi_user_id_9d4fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentauditlog',
            index=models.Index(fields=['action', 'created_at'], name='deploy_audi_action_c5f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentrequest',
            index=models.Index(fields=['owner', 'status'], name='deploy_requ_owner_i_21404d_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentrequest',
            index=models.Index(fields=['project_id'], name='deploy_requ_project_05b641_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentrequest',
            index=models.Index(fields=['created_at'], name='deploy_requ_created_a05d8f_idx'),
        ),
    ]
