# Generated by Django 6.0.2 on 2026-02-25 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pipeline_name', models.CharField(max_length=100)),
                ('pipeline_file', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pipelines',
            },
        ),
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='pipelines.pipeline')),
            ],
            options={
                'db_table': 'pipeline_jobs',
            },
        ),
        migrations.CreateModel(
            name='PipelineArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artifact_path', models.CharField(max_length=500)),
                ('storage_url', models.URLField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='pipelines.pipelinejob')),
            ],
            options={
                'db_table': 'pipeline_artifacts',
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pipelines.pipelinejob')),
            ],
            options={
                'db_table': 'job_logs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='PipelineRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_type', models.CharField(max_length=50)),
                ('rule_value', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_rules', to='pipelines.project')),
            ],
            options={
                'db_table': 'pipeline_rules',
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='pipelines.project'),
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('is_protected', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='pipelines.project')),
            ],
            options={
                'db_table': 'environments',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('repo_name', models.CharField(max_length=100)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='pipelines.project')),
            ],
            options={
                'db_table': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='PipelineFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('file_type', models.CharField(default='orcacloud', max_length=20)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_files', to='pipelines.repository')),
            ],
            options={
                'db_table': 'pipeline_files',
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='pipelines.repository'),
        ),
        migrations.CreateModel(
            name='PipelineApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approved_by', models.CharField(max_length=100)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pipelines.pipeline')),
            ],
            options={
                'db_table': 'pipeline_approvals',
                'indexes': [models.Index(fields=['pipeline', 'approved_at'], name='pipeline_ap_pipelin_9e219c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinejob',
            index=models.Index(fields=['pipeline', 'status'], name='pipeline_jo_pipelin_d52e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinejob',
            index=models.Index(fields=['status', 'started_at'], name='pipeline_jo_status_71a5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelineartifact',
            index=models.Index(fields=['job'], name='pipeline_ar_job_id_c95d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='joblog',
            index=models.Index(fields=['job', 'timestamp'], name='job_logs_job_id_41acd6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'name'], name='projects_owner_i_2301d8_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerule',
            index=models.Index(fields=['project', 'rule_type'], name='pipeline_ru_project_37658c_idx'),
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['project', 'is_protected'], name='environment_project_5d4745_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['project', 'provider'], name='repositorie_project_4b23e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('project', 'provider', 'repo_name')},
        ),
        migrations.AddIndex(
            model_name='pipelinefile',
            index=models.Index(fields=['repo', 'file_type'], name='pipeline_fi_repo_id_e619b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinefile',
            unique_together={('repo', 'path')},
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['project', 'status'], name='pipelines_project_912987_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['repo', 'branch'], name='pipelines_repo_id_4f34d5_idx'),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['status', 'started_at'], name='pipelines_status_ee522a_idx'),
        ),
    ]
