# Generated by Django 6.0.2 on 2026-03-01 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_environment_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('yaml_definition', models.TextField(blank=True, default='', help_text='Full YAML definition of the pipeline.')),
                ('variables', models.JSONField(default=list, help_text='List of {name, value, secret} variable dicts.')),
                ('triggers', models.JSONField(default=list, help_text='List of trigger configs (push, schedule, manual).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_definitions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_definitions', to='pipelines.project')),
            ],
            options={
                'db_table': 'pipeline_definitions',
            },
        ),
        migrations.CreateModel(
            name='PipelineDefinitionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('build', 'Build'), ('test', 'Test'), ('security', 'Security Scan'), ('deploy', 'Deploy'), ('verify', 'Verify'), ('notify', 'Notify'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('environment', models.CharField(blank=True, default='', help_text='Target environment for deploy stages.', max_length=100)),
                ('parallel', models.BooleanField(default=False, help_text="Run this stage's steps in parallel.")),
                ('condition', models.CharField(blank=True, default='', help_text='Expression determining whether this stage runs.', max_length=200)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipelines.pipelinedefinition')),
            ],
            options={
                'db_table': 'pipeline_definition_stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PipelineDefinitionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('script', 'Shell Script'), ('docker', 'Docker Build/Push'), ('kubernetes', 'Kubernetes Manifest'), ('approval', 'Manual Approval'), ('notification', 'Notification'), ('artifact', 'Artifact Upload'), ('test', 'Test Runner'), ('scan', 'Security Scan')], default='script', max_length=20)),
                ('script', models.TextField(blank=True, default='', help_text='Shell script body for script-type steps.')),
                ('config_json', models.JSONField(default=dict, help_text='Type-specific config (image, manifest, etc.).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('always', 'Always'), ('on_success', 'On Success'), ('on_failure', 'On Failure')], default='on_success', max_length=20)),
                ('timeout_seconds', models.PositiveIntegerField(default=3600)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipelines.pipelinedefinitionstage')),
            ],
            options={
                'db_table': 'pipeline_definition_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('waiting', 'Waiting Approval')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(max_length=120)),
                ('branch', models.CharField(blank=True, default='main', max_length=200)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('commit_msg', models.CharField(blank=True, default='', max_length=300)),
                ('variables', models.JSONField(default=dict, help_text='Run-time variable overrides.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pipelines.pipelinedefinition')),
            ],
            options={
                'db_table': 'pipeline_runs',
            },
        ),
        migrations.CreateModel(
            name='PipelineRunNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('stage', 'Stage'), ('step', 'Step')], default='step', max_length=10)),
                ('stage_name', models.CharField(max_length=100)),
                ('step_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('waiting', 'Waiting Approval'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('log_output', models.TextField(blank=True, default='')),
                ('error_msg', models.TextField(blank=True, default='')),
                ('artifacts', models.JSONField(default=list, help_text='List of {name, url} artifact references.')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pipelines.pipelinerun')),
            ],
            options={
                'db_table': 'pipeline_run_nodes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('artifact_type', models.CharField(blank=True, default='', help_text='docker_image, test_report, manifest, binary, etc.', max_length=50)),
                ('storage_url', models.URLField(blank=True, default='')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_artifacts', to='pipelines.pipelinerun')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_artifacts', to='pipelines.pipelinerunnode')),
            ],
            options={
                'db_table': 'pipeline_run_artifacts',
            },
        ),
        migrations.AddIndex(
            model_name='pipelinedefinition',
            index=models.Index(fields=['project', 'is_active'], name='pipeline_de_project_08677e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinedefinition',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinedefinitionstage',
            unique_together={('definition', 'name')},
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['definition', 'status'], name='pipeline_ru_definit_d66a18_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['status', 'started_at'], name='pipeline_ru_status_b5631c_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerunnode',
            index=models.Index(fields=['run', 'status'], name='pipeline_ru_run_id_07359f_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerunnode',
            index=models.Index(fields=['run', 'stage_name'], name='pipeline_ru_run_id_efae82_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerunartifact',
            index=models.Index(fields=['run', 'artifact_type'], name='pipeline_ru_run_id_797f1b_idx'),
        ),
    ]
