# Generated by Django 6.0.2 on 2026-03-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_pipeline_definition_run_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='pipelines.repository'),
        ),
    ]
