# Generated by Django 6.0.2 on 2026-03-02 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_add_repo_to_pipeline_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar_color',
            field=models.CharField(blank=True, default='#153d75', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='namespace',
            field=models.CharField(blank=True, default='', help_text='Kubernetes/org namespace auto-generated from owner+key.', max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='project_key',
            field=models.CharField(blank=True, default='', help_text='Short URL-safe identifier, e.g. "my-app".', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'project_key'], name='projects_owner_i_137cd4_idx'),
        ),
    ]
