# Generated by Django 6.0.2 on 2026-03-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_extend_project_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('orcacloud', 'OrcaCloud')], max_length=20),
        ),
    ]
