# Generated by Django 6.0.2 on 2026-03-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_repository_add_orcacloud_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='tree_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
