# Generated by Django 6.0.2 on 2026-03-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_repository_add_tree_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentAuditEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('resource', models.CharField(blank=True, default='', max_length=300)),
                ('result', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied')], default='success', max_length=20)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='pipelines.environment')),
            ],
            options={
                'db_table': 'environment_audit_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentDeployment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(default='manual', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='pipelines.environment')),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='env_deployments', to='pipelines.pipelinerun')),
            ],
            options={
                'db_table': 'environment_deployments',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=100)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_by', models.CharField(default='system', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='pipelines.environment')),
            ],
            options={
                'db_table': 'environment_releases',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='pipelines.environment')),
            ],
            options={
                'db_table': 'environment_feature_flags',
                'ordering': ['key'],
                'unique_together': {('environment', 'key')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('scaling', 'Scaling')], default='running', max_length=20)),
                ('replicas', models.IntegerField(default=1)),
                ('desired', models.IntegerField(default=1)),
                ('image', models.CharField(blank=True, default='', max_length=300)),
                ('cpu_pct', models.FloatField(default=0.0)),
                ('ram_mb', models.IntegerField(default=0)),
                ('endpoints', models.JSONField(blank=True, default=list)),
                ('last_log', models.TextField(blank=True, default='')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pipelines.environment')),
            ],
            options={
                'db_table': 'environment_services',
                'ordering': ['name'],
                'unique_together': {('environment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True, default='')),
                ('secret', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='pipelines.environment')),
            ],
            options={
                'db_table': 'environment_variables',
                'ordering': ['key'],
                'unique_together': {('environment', 'key')},
            },
        ),
    ]
