# Generated by Django 6.0.2 on 2026-03-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_environment_detail_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_type', models.CharField(choices=[('dockerfile', 'Dockerfile'), ('env', '.env / dotenv'), ('yaml', 'YAML / YML'), ('helm', 'Helm Chart'), ('k8s', 'Kubernetes Manifest'), ('terraform', 'Terraform'), ('compose', 'Docker Compose'), ('config', 'Config File'), ('properties', 'Properties File'), ('other', 'Other')], default='other', max_length=20)),
                ('associated_service', models.CharField(blank=True, default='', max_length=200)),
                ('is_valid', models.BooleanField(default=True)),
                ('has_errors', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_env_specific', models.BooleanField(default=False, help_text='True if this file contains env-specific overrides.')),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pipelines.environment')),
            ],
            options={
                'db_table': 'environment_files',
                'ordering': ['file_type', 'file_name'],
                'indexes': [models.Index(fields=['environment', 'file_type'], name='environment_environ_a097ee_idx'), models.Index(fields=['environment', 'is_valid'], name='environment_environ_b22311_idx')],
            },
        ),
    ]
