# Generated by Django 6.0.2 on 2026-03-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0010_sshkey_alter_repository_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.CharField(choices=[('personal', 'Personal'), ('workspace', 'Workspace'), ('group', 'Group')], default='personal', help_text='Creation context for provenance tracking.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who pressed "Create Project".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='group_id',
            field=models.CharField(blank=True, default='', help_text='Group ID this project belongs to.', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_id',
            field=models.CharField(blank=True, default='', help_text='workspace_id of the DevWorkspace this project was created in.', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='repository',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this repository.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repositories', to=settings.AUTH_USER_MODEL),
        ),
    ]
