# Generated by Django 6.0.2 on 2026-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0011_project_context_project_created_by_project_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='group_id',
            field=models.CharField(blank=True, default='', help_text='ID of the Group this repo was created in.', max_length=64),
        ),
        migrations.AddField(
            model_name='repository',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='repository',
            name='workspace_id',
            field=models.CharField(blank=True, default='', help_text='ID of the DevWorkspace this repo was created in.', max_length=64),
        ),
        migrations.AddField(
            model_name='repository',
            name='workspace_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
