# Generated by Django 6.0.2 on 2026-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0012_repository_group_id_repository_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by_role',
            field=models.CharField(choices=[('enterprise', 'Enterprise'), ('developer', 'Developer')], db_index=True, default='developer', help_text='Whether this project was created under an enterprise or developer identity.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_context_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Owning entity ID: enterprise org id, group id, or empty for personal.', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='return_path',
            field=models.CharField(blank=True, default='', help_text='Frontend URL the user navigates back to from this project.', max_length=500),
        ),
    ]
