# Generated by Django 6.0.2 on 2026-03-02 23:08

import django.db.models.deletion
import services.groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.groups.models._uid_pipeline, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('pipeline_type', models.CharField(choices=[('ci', 'Continuous Integration'), ('cd', 'Continuous Delivery'), ('ci_cd', 'CI/CD (Multi-stage)'), ('build', 'Build Only'), ('deploy', 'Deploy Only'), ('release', 'Release Pipeline'), ('rollback', 'Rollback Pipeline'), ('scheduled', 'Scheduled / Cron'), ('custom', 'Custom')], default='ci_cd', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('project_id', models.CharField(blank=True, default='', max_length=255)),
                ('project_name', models.CharField(blank=True, default='', max_length=200)),
                ('environment_targets', models.JSONField(default=list, help_text='List of environment IDs or slugs this pipeline can deploy to')),
                ('definition', models.JSONField(default=dict, help_text='Structured pipeline definition: {stages: [{name, steps: [...]}]}')),
                ('yaml_content', models.TextField(blank=True, default='')),
                ('triggers', models.JSONField(default=list, help_text='List of trigger configs: [{type, branch_pattern, schedule, ...}]')),
                ('upstream_pipeline_ids', models.JSONField(blank=True, default=list)),
                ('downstream_pipeline_ids', models.JSONField(blank=True, default=list)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_run_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('avg_duration_s', models.FloatField(default=0)),
                ('success_rate', models.FloatField(default=0, help_text='0–100 percentage')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='groups.group')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_pipeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupPipelineRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.groups.models._uid_run, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('trigger_source', models.CharField(choices=[('user', 'Manual Trigger'), ('webhook', 'Webhook'), ('schedule', 'Scheduled'), ('api', 'API'), ('upstream', 'Upstream Pipeline')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('pending', 'Pending Approval'), ('rolled_back', 'Rolled Back')], default='queued', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=200)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('commit_message', models.CharField(blank=True, default='', max_length=500)),
                ('environment_id', models.CharField(blank=True, default='', max_length=255)),
                ('environment_name', models.CharField(blank=True, default='', max_length=200)),
                ('workspace_id', models.CharField(blank=True, default='', max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('stages_snapshot', models.JSONField(blank=True, default=list, help_text='Per-stage status at run time: [{name, status, steps:[{name, status, log}]}]')),
                ('artifacts', models.JSONField(blank=True, default=list)),
                ('log_url', models.CharField(blank=True, default='', max_length=1024)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='groups.grouppipeline')),
                ('rolled_back_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_runs', to='groups.grouppipelinerun')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_pipeline_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='grouppipeline',
            index=models.Index(fields=['group', 'status'], name='groups_pipe_group_i_d90fef_idx'),
        ),
        migrations.AddIndex(
            model_name='grouppipeline',
            index=models.Index(fields=['group', 'pipeline_type'], name='groups_pipe_group_i_3a309c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouppipeline',
            unique_together={('group', 'slug')},
        ),
        migrations.AddIndex(
            model_name='grouppipelinerun',
            index=models.Index(fields=['pipeline', 'status'], name='groups_pipe_pipelin_d4c83c_idx'),
        ),
        migrations.AddIndex(
            model_name='grouppipelinerun',
            index=models.Index(fields=['pipeline', '-created_at'], name='groups_pipe_pipelin_6f755e_idx'),
        ),
    ]
