# Generated by Django 6.0.2 on 2026-03-01 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workspace_id'],
            },
        ),
        migrations.CreateModel(
            name='ProvisionedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=16)),
                ('resource_type', models.CharField(choices=[('vm', 'Virtual Machine'), ('volume', 'Block Storage Volume'), ('network', 'Network'), ('subnet', 'Subnet'), ('snapshot', 'Snapshot'), ('floating_ip', 'Floating IP'), ('k8s_cluster', 'Kubernetes Cluster')], max_length=32)),
                ('resource_id', models.CharField(help_text='OpenStack resource UUID', max_length=255)),
                ('resource_name', models.CharField(max_length=255)),
                ('openstack_project', models.CharField(max_length=128)),
                ('region', models.CharField(default='RegionOne', max_length=64)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'Active'), ('error', 'Error'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='creating', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='workspace.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'environment'], name='workspace_p_workspa_025f7d_idx'), models.Index(fields=['resource_type'], name='workspace_p_resourc_3e6c43_idx'), models.Index(fields=['resource_id'], name='workspace_p_resourc_ca8ff0_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('prod', 'Production')], max_length=16)),
                ('openstack_project', models.CharField(help_text='OpenStack project/tenant name', max_length=128)),
                ('openstack_region', models.CharField(default='RegionOne', max_length=64)),
                ('quota_vcpus', models.PositiveIntegerField(default=20)),
                ('quota_ram_gb', models.PositiveIntegerField(default=100)),
                ('quota_storage_gb', models.PositiveIntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='workspace.workspace')),
            ],
            options={
                'ordering': ['workspace', 'environment'],
                'unique_together': {('workspace', 'environment')},
            },
        ),
    ]
