# Generated by Django 6.0.2 on 2026-03-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('error', 'Error')], default='stopped', max_length=16)),
                ('region', models.CharField(default='us-east-1', max_length=64)),
                ('image', models.CharField(default='orcacloud/devbox:22.04-lts', max_length=200)),
                ('ide', models.CharField(default='VS Code', max_length=100)),
                ('editor_url', models.URLField(blank=True, default='')),
                ('cpu_percent', models.PositiveSmallIntegerField(default=0)),
                ('ram_percent', models.PositiveSmallIntegerField(default=0)),
                ('containers', models.PositiveSmallIntegerField(default=0)),
                ('volumes', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
