# Generated by Django 6.0.2 on 2026-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_workspacebinding_cloud_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devworkspace',
            name='connected_container_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of container IDs attached to this workspace.'),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='connected_env_id',
            field=models.CharField(blank=True, default='', help_text='Environment ID connected to this workspace.', max_length=64),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='connected_env_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='connected_group_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='connected_group_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='connected_project_id',
            field=models.CharField(blank=True, default='', help_text='Project ID / key connected to this workspace.', max_length=64),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='connected_project_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='pipeline_last_failure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='pipeline_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='pipeline_last_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='pipeline_last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='setup_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
