# Generated by Django 6.0.2 on 2026-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_devworkspace_provisioning_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='devworkspace',
            name='enterprise_org_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='enterprise.Organization.id that owns this workspace.', max_length=36),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='enterprise_org_slug',
            field=models.SlugField(blank=True, default='', help_text='Slug of the enterprise org (for URL routing).', max_length=100),
        ),
    ]
