# Generated by Django 6.0.2 on 2026-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_devworkspace_enterprise_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devworkspace',
            name='enterprise_org_id',
        ),
        migrations.RemoveField(
            model_name='devworkspace',
            name='enterprise_org_slug',
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='created_by_role',
            field=models.CharField(choices=[('enterprise', 'Enterprise'), ('developer', 'Developer')], db_index=True, default='developer', help_text='Role of the user who created this workspace.', max_length=20),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='created_from_dashboard',
            field=models.CharField(choices=[('enterprise', 'Enterprise Dashboard'), ('developer', 'Developer Dashboard'), ('group', 'Group Dashboard')], db_index=True, default='developer', help_text='Dashboard context in which this workspace was created.', max_length=20),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='parent_context_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Owning entity ID: enterprise org id, group id, or empty for personal.', max_length=100),
        ),
        migrations.AddField(
            model_name='devworkspace',
            name='return_path',
            field=models.CharField(blank=True, default='', help_text='Frontend URL the user navigates back to from this workspace.', max_length=500),
        ),
    ]
