# Generated by OrcaCloud — add cloud_type to WorkspaceBinding

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_dev_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacebinding",
            name="cloud_type",
            field=models.CharField(
                choices=[
                    ("public",  "Public Cloud"),
                    ("private", "Private Cloud"),
                    ("hybrid",  "Hybrid Cloud"),
                ],
                db_index=True,
                default="public",
                help_text="Determines which service catalog entries are available for this binding.",
                max_length=16,
            ),
        ),
    ]
