# Generated by Django 6.0.2 on 2026-03-01 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudRegion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Short unique code, e.g. us-east-1', max_length=32, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('continent', models.CharField(blank=True, max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('maintenance', 'Maintenance'), ('unavailable', 'Unavailable')], db_index=True, default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default region for new resources')),
                ('uptime_30d_pct', models.FloatField(default=100.0)),
                ('latency_ms', models.FloatField(blank=True, help_text='Average inter-region latency observed from this region', null=True)),
                ('enabled_services', models.JSONField(default=list, help_text='e.g. ["compute","storage","database","kubernetes"]')),
                ('api_endpoint', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Cloud Region',
                'ordering': ['continent', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. a, b, c', max_length=8)),
                ('name', models.CharField(help_text='e.g. us-east-1a', max_length=64)),
                ('status', models.CharField(choices=[('available', 'Available'), ('impaired', 'Impaired'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='regions.cloudregion')),
            ],
            options={
                'verbose_name': 'Availability Zone',
                'ordering': ['region__code', 'code'],
                'unique_together': {('region', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RegionPeer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('active-active', 'Active–Active'), ('active-passive', 'Active–Passive'), ('cold-standby', 'Cold Standby')], default='active-passive', max_length=20)),
                ('rto_minutes', models.PositiveIntegerField(default=15, help_text='Recovery Time Objective in minutes')),
                ('rpo_minutes', models.PositiveIntegerField(default=5, help_text='Recovery Point Objective in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failover_pairs_as_primary', to='regions.cloudregion')),
                ('secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failover_pairs_as_secondary', to='regions.cloudregion')),
            ],
            options={
                'verbose_name': 'Region Peer',
                'ordering': ['-created_at'],
                'unique_together': {('primary', 'secondary')},
            },
        ),
    ]
