# OrcaCloud — Deploy Service Serializers

from rest_framework import serializers
from django.contrib.auth.models import User

from .models import (
    DeploymentTemplate, DeploymentRequest, DeploymentPlan,
    DeploymentExecution, DeploymentAuditLog,
)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

class MinimalUserSerializer(serializers.ModelSerializer):
    class Meta:
        model  = User
        fields = ('id', 'username', 'email')


# ─────────────────────────────────────────────────────────────────────────────
# 1.  DeploymentTemplate
# ─────────────────────────────────────────────────────────────────────────────

class DeploymentTemplateSerializer(serializers.ModelSerializer):
    class Meta:
        model  = DeploymentTemplate
        fields = [
            'id', 'name', 'frontend', 'backend', 'database', 'deploy_mode',
            'runtime_image', 'install_command', 'build_commands', 'start_command',
            'health_check_path', 'health_check_port', 'readiness_delay_sec', 'app_port',
            'default_replicas', 'min_replicas', 'max_replicas', 'cpu_threshold_pct',
            'cpu_request', 'cpu_limit', 'memory_request', 'memory_limit',
            'default_env_vars', 'is_active', 'created_at', 'updated_at',
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']


# ─────────────────────────────────────────────────────────────────────────────
# 2.  DeploymentPlan  (read-only  — generated by logic layer, never submitted)
# ─────────────────────────────────────────────────────────────────────────────

class DeploymentPlanSerializer(serializers.ModelSerializer):
    class Meta:
        model  = DeploymentPlan
        fields = [
            'id', 'request',
            'build_steps', 'deploy_steps', 'env_vars', 'secrets',
            'infra_resources', 'monitoring_rules', 'scaling_rules',
            'rollback_strategy', 'ci_pipeline_def', 'security_posture',
            'dockerfile', 'k8s_manifests', 'app_url',
            'created_at', 'updated_at',
        ]
        read_only_fields = fields


class DeploymentPlanLiteSerializer(serializers.ModelSerializer):
    """Stripped plan for inline embedding in request detail."""
    class Meta:
        model  = DeploymentPlan
        fields = ['id', 'app_url', 'build_steps', 'deploy_steps', 'created_at']
        read_only_fields = fields


# ─────────────────────────────────────────────────────────────────────────────
# 3.  DeploymentExecution
# ─────────────────────────────────────────────────────────────────────────────

class DeploymentExecutionSerializer(serializers.ModelSerializer):
    class Meta:
        model  = DeploymentExecution
        fields = [
            'id', 'plan', 'environment', 'status',
            'pipeline_id', 'pipeline_run_id',
            'created_resources', 'log_lines',
            'started_at', 'finished_at', 'rolled_back_at',
            'app_hostname', 'app_url', 'health_status',
            'created_at', 'updated_at',
        ]
        read_only_fields = fields

    def to_representation(self, instance):
        rep = super().to_representation(instance)
        # Mask secrets in log lines (key=value pattern)
        rep['log_lines'] = [
            {**ln, 'text': _mask_secrets(ln.get('text', ''))}
            for ln in rep['log_lines']
        ]
        return rep


def _mask_secrets(text: str) -> str:
    """Redact common secret patterns in log output."""
    import re
    return re.sub(r'(?i)(password|secret|token|key)=[^\s&*]+', r'\1=***', text)


# ─────────────────────────────────────────────────────────────────────────────
# 4.  DeploymentAuditLog  (read-only)
# ─────────────────────────────────────────────────────────────────────────────

class DeploymentAuditLogSerializer(serializers.ModelSerializer):
    user = MinimalUserSerializer(read_only=True)

    class Meta:
        model  = DeploymentAuditLog
        fields = [
            'id', 'user', 'action', 'detail', 'ip_address',
            'request', 'execution', 'created_at',
        ]
        read_only_fields = fields


# ─────────────────────────────────────────────────────────────────────────────
# 5.  DeploymentRequest  (writer + reader)
# ─────────────────────────────────────────────────────────────────────────────

class DeploymentRequestCreateSerializer(serializers.ModelSerializer):
    """
    Used for POST /deploy/requests/
    The owner is inferred from the authenticated user.
    """
    class Meta:
        model  = DeploymentRequest
        fields = [
            'source', 'frontend', 'backend', 'database', 'deploy_mode',
            'app_type', 'description',
            'project_id', 'new_project_name', 'group_id',
            'git_repo', 'git_branch', 'target_environments',
        ]

    def validate_target_environments(self, value):
        allowed = {'dev', 'stage', 'prod', 'local'}
        if not isinstance(value, list) or not all(e in allowed for e in value):
            raise serializers.ValidationError(
                f'target_environments must be a list containing any of: {allowed}'
            )
        return value


class DeploymentRequestSerializer(serializers.ModelSerializer):
    """
    Full representation returned on GET.
    Embeds owner, plan summary, and execution list.
    """
    owner  = MinimalUserSerializer(read_only=True)
    plan   = DeploymentPlanLiteSerializer(read_only=True)
    executions = DeploymentExecutionSerializer(many=True, read_only=True)
    app_name   = serializers.SerializerMethodField()

    class Meta:
        model  = DeploymentRequest
        fields = [
            'id', 'owner', 'source',
            'frontend', 'backend', 'database', 'deploy_mode',
            'app_type', 'description',
            'project_id', 'new_project_name', 'group_id',
            'git_repo', 'git_branch', 'target_environments',
            'status', 'template',
            'app_name',
            'plan', 'executions',
            'created_at', 'updated_at',
        ]
        read_only_fields = [
            'id', 'owner', 'status', 'template',
            'app_name', 'plan', 'executions',
            'created_at', 'updated_at',
        ]

    def get_app_name(self, obj):
        return obj.app_name


class DeploymentRequestUpdateSerializer(serializers.ModelSerializer):
    """Partial update — only mutable fields before 'planned' status."""
    class Meta:
        model  = DeploymentRequest
        fields = [
            'description', 'git_repo', 'git_branch',
            'target_environments',
        ]

    def validate(self, data):
        obj = self.instance
        if obj and obj.status not in ('draft', 'pending'):
            raise serializers.ValidationError(
                'A deployment request can only be edited before planning stage.'
            )
        return data
