apiVersion: v1
kind: Service
metadata:
  name: orcacloud-backend
  namespace: orcacloud
  labels:
    app: orcacloud-backend
spec:
  selector:
    app: orcacloud-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
