apiVersion: v1
kind: Service
metadata:
  name: orcacloud-frontend
  namespace: orcacloud
  labels:
    app: orcacloud-frontend
spec:
  selector:
    app: orcacloud-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
