apiVersion: apps/v1
kind: Deployment
metadata:
  name: orcacloud-nginx
  namespace: orcacloud
  labels:
    app: orcacloud-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orcacloud-nginx
  template:
    metadata:
      labels:
        app: orcacloud-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: app-media
              mountPath: /var/www/media
      volumes:
        - name: nginx-config
          configMap:
            name: orcacloud-nginx-config
            items:
              - key: default.conf
                path: default.conf
        - name: app-media
          persistentVolumeClaim:
            claimName: orcacloud-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: orcacloud-nginx
  namespace: orcacloud
spec:
  selector:
    app: orcacloud-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
