apiVersion: v1
kind: Secret
metadata:
  name: orcacloud-secrets
  namespace: orcacloud
type: Opaque
stringData:
  SECRET_KEY: "REPLACE_ME_WITH_A_SECRET"
  POSTGRES_DB: "orcacloud"
  POSTGRES_USER: "orcacloud_user"
  POSTGRES_PASSWORD: "orcacloud_password"
