# Generated by Django 6.0.2 on 2026-03-05 03:21

import django.db.models.deletion
import services.enterprise.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._brnd_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=255)),
                ('primary_color', models.CharField(default='#153d75', max_length=7)),
                ('secondary_color', models.CharField(default='#1e3a5f', max_length=7)),
                ('accent_color', models.CharField(default='#3b82f6', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('font_family', models.CharField(default='IBM Plex Sans', max_length=100)),
                ('custom_css', models.TextField(blank=True, help_text='Additional CSS injected into branded pages')),
            ],
            options={
                'verbose_name': 'Branding Profile',
            },
        ),
        migrations.CreateModel(
            name='EnterprisePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._plan_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limits', models.JSONField(default=dict, help_text='{"members": 500, "teams": 50, ...}')),
                ('features', models.JSONField(default=list, help_text='Marketing feature bullets')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enterprise Plan',
            },
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._bast_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LOGO', 'Logo'), ('ICON', 'Icon'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document')], max_length=20)),
                ('url', models.URLField()),
                ('label', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('branding_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='enterprise.brandingprofile')),
            ],
            options={
                'verbose_name': 'Brand Asset',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._dept_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('department_lead', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='enterprise.department')),
            ],
            options={
                'verbose_name': 'Department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentSidebarItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._dsbi_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('navigation', 'Navigation'), ('action', 'Quick Action'), ('resource', 'Resource'), ('highlight', 'Highlight'), ('custom', 'Custom Link')], default='navigation', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_items', to='enterprise.department')),
            ],
            options={
                'verbose_name': 'Department Sidebar Item',
                'ordering': ['item_type', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._org_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('primary_domain', models.CharField(blank=True, max_length=253)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('plan', models.CharField(default='Enterprise', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial')], default='TRIAL', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('domain_email', models.EmailField(blank=True, default='', help_text='Primary organization email, e.g. admin@acme.com', max_length=254)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._einv_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='DUE', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pdf_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_invoices', to='enterprise.organization')),
            ],
            options={
                'verbose_name': 'Enterprise Invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='enterprise.organization'),
        ),
        migrations.AddField(
            model_name='brandingprofile',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='enterprise.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._mbr_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended')], default='INVITED', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.JSONField(default=dict, help_text='Per-module permission overrides')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='enterprise.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'unique_together': {('organization', 'email')},
            },
        ),
        migrations.CreateModel(
            name='OrgDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._odom_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=253)),
                ('type', models.CharField(choices=[('APP', 'Application'), ('MARKETING', 'Marketing'), ('EMAIL', 'Email'), ('MIXED', 'Mixed')], default='MIXED', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_DNS', 'Pending DNS'), ('ACTIVE', 'Active'), ('FAILED', 'Failed')], default='PENDING_DNS', max_length=20)),
                ('linked_apps', models.JSONField(default=list, help_text='List of app/service names this domain is linked to')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_domains', to='enterprise.organization')),
            ],
            options={
                'verbose_name': 'Organization Domain',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrgDomainRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._drec_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'A'), ('CNAME', 'CNAME'), ('TXT', 'TXT'), ('MX', 'MX')], max_length=10)),
                ('name', models.CharField(max_length=253)),
                ('value', models.TextField()),
                ('ttl', models.PositiveIntegerField(default=3600)),
                ('managed_by_platform', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='enterprise.orgdomain')),
            ],
            options={
                'verbose_name': 'Domain Record',
            },
        ),
        migrations.CreateModel(
            name='OrgTeam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._team_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('team_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('FUNCTION', 'Function'), ('SQUAD', 'Squad')], default='SQUAD', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='enterprise.department')),
            ],
            options={
                'verbose_name': 'Team',
                'ordering': ['name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._sub_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='TRIALING', max_length=20)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, help_text='Stripe subscription ID etc.', max_length=128)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='enterprise.organization')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='enterprise.enterpriseplan')),
            ],
            options={
                'verbose_name': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._wcat_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for UI badge', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_categories', to='enterprise.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._wpage_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content')),
                ('summary', models.CharField(blank=True, default='', help_text='Short description / excerpt', max_length=500)),
                ('is_pinned', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(default=list, help_text='Free-form tag strings, e.g. ["policy","hr"]')),
                ('linked_module', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='enterprise.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiPageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.wikicategory')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.wikipage')),
            ],
            options={
                'unique_together': {('page', 'category')},
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='pages', through='enterprise.WikiPageCategory', to='enterprise.wikicategory'),
        ),
        migrations.CreateModel(
            name='WikiPageVersion',
            fields=[
                ('id', models.CharField(default=services.enterprise.models._wver_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('edited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version_note', models.CharField(blank=True, default='', max_length=255)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='enterprise.wikipage')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSendDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._sed_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('status', models.CharField(choices=[('PENDING_DNS', 'Pending DNS'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING_DNS', max_length=20)),
                ('dkim_record', models.TextField(blank=True, help_text='Full TXT record value for DKIM')),
                ('spf_record', models.TextField(blank=True, help_text='TXT value for SPF')),
                ('tracking_domain', models.CharField(blank=True, help_text='Subdomain for open/click tracking', max_length=253)),
                ('selector', models.CharField(default='s1', max_length=64)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_domains', to='enterprise.organization')),
            ],
            options={
                'verbose_name': 'Enterprise Send Domain',
                'unique_together': {('organization', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='EmailSenderIdentity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._esi_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verify_token', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_identities', to='enterprise.organization')),
            ],
            options={
                'verbose_name': 'Email Sender Identity',
                'unique_together': {('organization', 'email')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._elog_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=998)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked')], default='QUEUED', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='enterprise.organization')),
            ],
            options={
                'verbose_name': 'Email Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='enterprise__organiz_9af8f1_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'name')},
        ),
        migrations.CreateModel(
            name='EnterpriseEmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._etpl_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=998)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('variables', models.JSONField(default=list, help_text='List of variable names used in template')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='enterprise.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='enterprise.organizationmember')),
            ],
            options={
                'verbose_name': 'Enterprise Email Template',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EnterpriseAuditLog',
            fields=[
                ('id', models.CharField(default=services.enterprise.models._aud_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, help_text='Denormalized email for deleted members', max_length=254)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='enterprise.organization')),
                ('actor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='enterprise.organizationmember')),
            ],
            options={
                'verbose_name': 'Enterprise Audit Log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', '-timestamp'], name='enterprise__organiz_821fef_idx'), models.Index(fields=['organization', 'action'], name='enterprise__organiz_85148e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrgGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._grp_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='enterprise.orgteam')),
            ],
            options={
                'verbose_name': 'Group',
                'ordering': ['name'],
                'unique_together': {('team', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['organization', '-updated_at'], name='enterprise__organiz_a700e1_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['organization', 'title'], name='enterprise__organiz_095e76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('organization', 'slug')},
        ),
    ]
