# Generated by Django 6.0.2 on 2026-03-05 03:51

import django.db.models.deletion
import services.enterprise.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._intc_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, help_text='e.g. stripe, sendgrid, slack', max_length=80)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(default='other', help_text='payments | email | domains | communication | development | marketing | identity | monitoring | crm | productivity | support | other', max_length=50)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error'), ('PENDING', 'Pending')], db_index=True, default='DISCONNECTED', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Encrypted-at-rest credential fields')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific settings')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='HMAC secret for incoming webhooks', max_length=128)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='enterprise.organization')),
            ],
            options={
                'ordering': ['provider'],
                'unique_together': {('organization', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.CharField(default=services.enterprise.models._intl_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=80)),
                ('event_type', models.CharField(choices=[('API_CALL', 'API Call'), ('WEBHOOK', 'Webhook Received'), ('TOKEN_REFRESH', 'Token Refresh'), ('SYNC', 'Data Sync'), ('CONNECT', 'Connection'), ('DISCONNECT', 'Disconnection'), ('TEST', 'Connection Test'), ('ERROR', 'Error')], max_length=30)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='enterprise.integrationconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_logs', to='enterprise.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', '-timestamp'], name='enterprise__organiz_1c2a5e_idx'), models.Index(fields=['organization', 'provider', '-timestamp'], name='enterprise__organiz_77bddc_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationWebhookEvent',
            fields=[
                ('id', models.CharField(default=services.enterprise.models._intwh_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=80)),
                ('event_type', models.CharField(max_length=120)),
                ('event_id', models.CharField(blank=True, default='', help_text='Provider event ID for deduplication', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('normalized', models.JSONField(default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='enterprise.integrationconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='enterprise.organization')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['organization', 'provider', '-received_at'], name='enterprise__organiz_af7bd7_idx')],
            },
        ),
    ]
