# Generated by Django 6.0.2 on 2026-03-05 14:08

import django.db.models.deletion
import services.enterprise.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_orgorder_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._mtg_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('agenda', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('recurring', 'Recurring'), ('instant', 'Instant'), ('department', 'Department')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('video_room_id', models.CharField(blank=True, default='', max_length=255)),
                ('video_provider', models.CharField(blank=True, default='livekit', help_text='livekit | twilio | daily | webrtc', max_length=50)),
                ('video_join_url', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, default='', help_text='RRULE string e.g. FREQ=WEEKLY;BYDAY=MO', max_length=255)),
                ('recording_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='enterprise.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='enterprise.organization')),
            ],
            options={
                'verbose_name': 'Meeting',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._mtn_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('invite', 'Meeting Invite'), ('reminder', 'Reminder'), ('updated', 'Meeting Updated'), ('cancelled', 'Meeting Cancelled'), ('started', 'Meeting Started'), ('recording', 'Recording Ready'), ('notes', 'Notes Added')], max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='enterprise.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._mtp_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', help_text='For external invitees', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-host'), ('attendee', 'Attendee')], default='attendee', max_length=20)),
                ('invite_status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('attended', 'Attended'), ('no_show', 'No Show')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='enterprise.meeting')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_participations', to='enterprise.organizationmember')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Participant',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._ann_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Null = org-wide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='enterprise.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='enterprise.organization')),
            ],
            options={
                'verbose_name': 'Announcement',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='enterprise__organiz_7dd8fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'start_time'], name='enterprise__organiz_007152_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'status'], name='enterprise__organiz_07526b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'email'), ('meeting', 'user')},
        ),
    ]
