# Generated by Django 6.0.2 on 2026-03-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_meeting_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wikipagecategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wikipagecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wikipagecategory',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='departmentsidebaritem',
            options={'ordering': ['order_index'], 'verbose_name': 'Department Sidebar Item'},
        ),
        migrations.AlterModelOptions(
            name='integrationconnection',
            options={'verbose_name': 'Integration Connection'},
        ),
        migrations.AlterModelOptions(
            name='integrationlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Integration Log'},
        ),
        migrations.AlterModelOptions(
            name='integrationwebhookevent',
            options={'ordering': ['-received_at'], 'verbose_name': 'Integration Webhook Event'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-start_time'], 'verbose_name': 'Meeting'},
        ),
        migrations.AlterModelOptions(
            name='meetingnotification',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Meeting Notification'},
        ),
        migrations.AlterModelOptions(
            name='meetingparticipant',
            options={'verbose_name': 'Meeting Participant'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item'},
        ),
        migrations.AlterModelOptions(
            name='orggroup',
            options={'verbose_name': 'Organization Group'},
        ),
        migrations.AlterModelOptions(
            name='orgorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization Order'},
        ),
        migrations.AlterModelOptions(
            name='orgteam',
            options={'verbose_name': 'Organization Team'},
        ),
        migrations.AlterModelOptions(
            name='wikicategory',
            options={'verbose_name': 'Wiki Category'},
        ),
        migrations.AlterModelOptions(
            name='wikipage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wiki Page'},
        ),
        migrations.AlterModelOptions(
            name='wikipageversion',
            options={'ordering': ['-edited_at'], 'verbose_name': 'Wiki Page Version'},
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='enterprise__organiz_7dd8fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationlog',
            name='enterprise__organiz_1c2a5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationlog',
            name='enterprise__organiz_77bddc_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationwebhookevent',
            name='enterprise__organiz_af7bd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='enterprise__organiz_007152_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='enterprise__organiz_07526b_idx',
        ),
        migrations.RemoveIndex(
            model_name='wikipage',
            name='enterprise__organiz_a700e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='wikipage',
            name='enterprise__organiz_095e76_idx',
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'email')},
        ),
        migrations.RemoveField(
            model_name='meetingnotification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meetingnotification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orggroup',
            name='owner',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='enterprise.department'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='departmentsidebaritem',
            name='icon',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='departmentsidebaritem',
            name='item_type',
            field=models.CharField(choices=[('LINK', 'Link'), ('HEADER', 'Header'), ('DIVIDER', 'Divider')], default='LINK', max_length=20),
        ),
        migrations.AlterField(
            model_name='departmentsidebaritem',
            name='order_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departmentsidebaritem',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='connected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='credentials',
            field=models.JSONField(default=dict, help_text='Encrypted at rest; never expose to client'),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='status',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='total_calls',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='event_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='level',
            field=models.CharField(default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='provider',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='integrationlog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='integrationwebhookevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='integrationwebhookevent',
            name='event_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='integrationwebhookevent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integrationwebhookevent',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='integrationwebhookevent',
            name='provider',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('STANDUP', 'Standup'), ('REVIEW', 'Review'), ('PLANNING', 'Planning'), ('ONE_ON_ONE', '1:1'), ('ALL_HANDS', 'All Hands'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='video_join_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='video_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='video_room_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='meetingnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetingnotification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingnotification',
            name='notif_type',
            field=models.CharField(default='REMINDER', max_length=40),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='invite_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.organizationmember'),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('ATTENDEE', 'Attendee'), ('OPTIONAL', 'Optional')], default='ATTENDEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='domain_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='orgorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orgorder',
            name='order_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='orgorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FULFILLED', 'Fulfilled'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='linked_module',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wikipageversion',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikipageversion',
            name='edited_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wikipageversion',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wikipageversion',
            name='version_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='WikiPageCategory',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='pages', to='enterprise.wikicategory'),
        ),
        migrations.RemoveField(
            model_name='integrationlog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='integrationlog',
            name='request_data',
        ),
        migrations.RemoveField(
            model_name='integrationlog',
            name='response_data',
        ),
        migrations.RemoveField(
            model_name='integrationwebhookevent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='updated_at',
        ),
    ]
