# Generated by Django 6.0.2 on 2026-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_alter_wikipagecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='notification_slack_webhook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='notifications_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='notifications_security',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='notifications_usage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
