# Generated by Django 6.0.2 on 2026-02-25 18:09

import django.db.models.deletion
import services.containers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.containers.models.gen_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('container_type', models.CharField(choices=[('runtime', 'Runtime'), ('worker', 'Worker'), ('cron', 'Cron'), ('oneoff', 'One-off')], default='runtime', max_length=20)),
                ('project_id', models.CharField(blank=True, max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=150)),
                ('pipeline', models.CharField(blank=True, max_length=150)),
                ('image', models.CharField(max_length=500)),
                ('image_tag', models.CharField(default='latest', max_length=100)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('cpu', models.FloatField(default=0.5)),
                ('memory', models.IntegerField(default=512)),
                ('replicas', models.IntegerField(default=1)),
                ('autoscaling', models.BooleanField(default=False)),
                ('autoscale_min', models.IntegerField(default=1)),
                ('autoscale_max', models.IntegerField(default=10)),
                ('autoscale_cpu', models.IntegerField(default=70)),
                ('expose', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('private', 'Private')], default='internal', max_length=20)),
                ('port', models.IntegerField(default=8080)),
                ('domain', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('running', 'Running'), ('deploying', 'Deploying'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='stopped', max_length=20)),
                ('last_deployed', models.DateTimeField(blank=True, null=True)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('runtime_meta', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'containers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerDeployment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.containers.models.gen_dep_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('trigger', models.CharField(default='manual', max_length=100)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('image_tag', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='containers.container')),
            ],
            options={
                'db_table': 'container_deployments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['owner', 'status'], name='containers_owner_i_65ef2a_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['project_id'], name='containers_project_8d4589_idx'),
        ),
    ]
