# Generated by Django 6.0.2 on 2026-03-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_environmentfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('public_key', models.TextField()),
                ('fingerprint', models.CharField(blank=True, max_length=200)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ssh_keys',
            },
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='repository',
            name='disk_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='repository',
            name='is_bare',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repository',
            name='storage_bucket',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='repository',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('team', 'Team')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='pipelines.project'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('atonix', 'OrcaCloud')], default='atonix', max_length=20),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['owner'], name='repositorie_owner_i_f7dc4a_idx'),
        ),
        migrations.AddField(
            model_name='sshkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sshkey',
            unique_together={('user', 'fingerprint')},
        ),
    ]
