# Generated by Django 6.0.2 on 2026-02-25 18:56

import django.db.models.deletion
import services.kubernetes_integration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KubeConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.kubernetes_integration.models._kube_id, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=60)),
                ('project_name', models.CharField(blank=True, max_length=150)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=30)),
                ('cluster_id', models.CharField(blank=True, help_text='Cluster identifier / context name', max_length=150)),
                ('cluster_name', models.CharField(blank=True, max_length=150)),
                ('namespace', models.CharField(blank=True, help_text='Derived from project slug + env', max_length=150)),
                ('git_provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'), ('other', 'Other')], default='github', max_length=20)),
                ('git_repo', models.CharField(blank=True, help_text='owner/repo', max_length=300)),
                ('git_branch', models.CharField(default='main', max_length=150)),
                ('git_path', models.CharField(default='k8s/', help_text='Path inside repo to scan', max_length=300)),
                ('last_commit', models.CharField(blank=True, max_length=40)),
                ('last_sync_status', models.CharField(choices=[('never', 'Never synced'), ('pending', 'Pending'), ('scanning', 'Scanning'), ('syncing', 'Syncing'), ('success', 'Success'), ('failed', 'Failed')], default='never', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('auto_apply', models.BooleanField(default=False, help_text='Apply without human confirmation (e.g. dev/staging)')),
                ('governance_warnings', models.JSONField(default=list, help_text='Last governance warning list')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kube_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kube_configs',
            },
        ),
        migrations.CreateModel(
            name='KubeSyncRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.kubernetes_integration.models._sync_id, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('scan', 'Scan'), ('apply', 'Apply'), ('ci_scan', 'CI/CD Scan'), ('ci_apply', 'CI/CD Apply')], default='apply', max_length=20)),
                ('triggered_by', models.CharField(default='manual', help_text='username or "ci/cd"', max_length=150)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('files_selected', models.JSONField(default=list, help_text='List of file paths user confirmed')),
                ('files_applied', models.JSONField(default=list, help_text='Files successfully applied')),
                ('resources_created', models.JSONField(default=list, help_text='[{kind, name, namespace}]')),
                ('governance_issues', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('kube_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='kubernetes_integration.kubeconfig')),
            ],
            options={
                'db_table': 'kube_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kubeconfig',
            index=models.Index(fields=['owner', 'project_id'], name='kube_config_owner_i_ce73ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kubeconfig',
            unique_together={('project_id', 'environment')},
        ),
        migrations.AddIndex(
            model_name='kubesyncrun',
            index=models.Index(fields=['kube_config', '-started_at'], name='kube_sync_r_kube_co_c96e30_idx'),
        ),
    ]
