"""
OrcaCloud AI/ML service models.

Provides:
  - AnomalyDetectionRule  – per-user metric watch configuration
  - AnomalyEvent          – recorded anomaly occurrences
  - ScalingPrediction     – predicted upcoming scale events for an ASG
  - AIRecommendation      – cost / performance / security suggestions
"""
import uuid
from django.db import models
from django.contrib.auth.models import User

from ..core.base_models import TimeStampedModel


# ---------------------------------------------------------------------------
# Choices
# ---------------------------------------------------------------------------

METRIC_CHOICES = [
    ('cpu_usage_percent',    'CPU Utilisation %'),
    ('memory_usage_percent', 'Memory Utilisation %'),
    ('disk_usage_percent',   'Disk Utilisation %'),
    ('network_in_bytes',     'Network In (bytes)'),
    ('network_out_bytes',    'Network Out (bytes)'),
]

SEVERITY_CHOICES = [
    ('info',     'Info'),
    ('warning',  'Warning'),
    ('critical', 'Critical'),
]

RECOMMENDATION_TYPE_CHOICES = [
    ('cost',        'Cost Optimisation'),
    ('performance', 'Performance'),
    ('security',    'Security'),
    ('reliability', 'Reliability'),
]

PREDICTION_DIRECTION_CHOICES = [
    ('scale_up',   'Scale Up'),
    ('scale_down', 'Scale Down'),
    ('maintain',   'Maintain'),
]


# ---------------------------------------------------------------------------
# AnomalyDetectionRule
# ---------------------------------------------------------------------------

class AnomalyDetectionRule(TimeStampedModel):
    """
    User-defined rule that triggers an AnomalyEvent when a metric
    deviates beyond ``z_score_threshold`` standard deviations from the
    rolling average over ``lookback_minutes``.
    """
    id             = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner          = models.ForeignKey(User, on_delete=models.CASCADE, related_name='anomaly_rules')
    name           = models.CharField(max_length=128)
    description    = models.TextField(blank=True)
    metric         = models.CharField(max_length=40, choices=METRIC_CHOICES, default='cpu_usage_percent')
    # Optional: scope rule to a specific instance (NULL = all instances)
    instance_id    = models.CharField(max_length=64, blank=True, null=True, db_index=True,
                                      help_text='Leave blank to watch all instances owned by this user')
    lookback_minutes    = models.PositiveIntegerField(default=60,
                                                       help_text='Window (minutes) used to compute rolling baseline')
    z_score_threshold   = models.FloatField(default=2.5,
                                             help_text='How many std-devs above the rolling mean counts as anomalous')
    min_sample_count    = models.PositiveIntegerField(default=5,
                                                       help_text='Minimum data points required before evaluation fires')
    is_active      = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Anomaly Detection Rule'

    def __str__(self):
        return f"{self.name} ({self.metric})"


# ---------------------------------------------------------------------------
# AnomalyEvent
# ---------------------------------------------------------------------------

class AnomalyEvent(TimeStampedModel):
    """
    Recorded anomaly triggered by an AnomalyDetectionRule.
    """
    id           = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    rule         = models.ForeignKey(AnomalyDetectionRule, on_delete=models.CASCADE, related_name='events')
    instance_id  = models.CharField(max_length=64, db_index=True)
    metric       = models.CharField(max_length=40, choices=METRIC_CHOICES)
    observed_value   = models.FloatField()
    baseline_mean    = models.FloatField()
    baseline_std     = models.FloatField()
    z_score          = models.FloatField()
    severity     = models.CharField(max_length=10, choices=SEVERITY_CHOICES, default='warning')
    resolved_at  = models.DateTimeField(null=True, blank=True)
    notes        = models.TextField(blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Anomaly Event'

    def __str__(self):
        return f"Anomaly on {self.instance_id} [{self.metric}] z={self.z_score:.2f}"


# ---------------------------------------------------------------------------
# ScalingPrediction
# ---------------------------------------------------------------------------

class ScalingPrediction(TimeStampedModel):
    """
    Predictive scaling record generated by the AI engine for an ASG.

    The ``predicted_at`` field marks when the model generated the prediction;
    ``target_time`` is the predicted wall-clock moment when the scaling event
    will be needed; ``horizon_minutes`` is the lookahead window used.
    """
    id                 = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner              = models.ForeignKey(User, on_delete=models.CASCADE, related_name='scaling_predictions')
    asg_id             = models.CharField(max_length=64, db_index=True,
                                          help_text='AutoScalingGroup.asg_id this prediction targets')
    direction          = models.CharField(max_length=12, choices=PREDICTION_DIRECTION_CHOICES)
    predicted_metric   = models.CharField(max_length=40, choices=METRIC_CHOICES)
    predicted_value    = models.FloatField(help_text='Forecasted metric value at target_time')
    current_capacity   = models.IntegerField(default=0)
    recommended_capacity = models.IntegerField(default=0)
    confidence_pct     = models.FloatField(default=0.0,
                                           help_text='Model confidence score 0-100')
    horizon_minutes    = models.PositiveIntegerField(default=30)
    target_time        = models.DateTimeField(null=True, blank=True)
    acted_upon         = models.BooleanField(default=False,
                                             help_text='True once auto-scaler has applied this recommendation')

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Scaling Prediction'

    def __str__(self):
        return f"Prediction[{self.direction}] for ASG {self.asg_id}"


# ---------------------------------------------------------------------------
# AIRecommendation
# ---------------------------------------------------------------------------

class AIRecommendation(TimeStampedModel):
    """
    Actionable recommendation produced by the AI engine.
    Covers cost, performance, reliability, and security concerns.
    """
    id              = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ai_recommendations')
    rec_type        = models.CharField(max_length=20, choices=RECOMMENDATION_TYPE_CHOICES)
    title           = models.CharField(max_length=255)
    description     = models.TextField()
    resource_type   = models.CharField(max_length=60, blank=True,
                                       help_text='e.g. Instance, AutoScalingGroup, StorageBucket')
    resource_id     = models.CharField(max_length=64, blank=True)
    estimated_saving_usd = models.DecimalField(
        max_digits=10, decimal_places=2, default=0,
        help_text='Estimated monthly USD saving (0 for non-cost recommendations)',
    )
    priority        = models.CharField(
        max_length=10,
        choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')],
        default='medium',
    )
    is_dismissed    = models.BooleanField(default=False)
    dismissed_at    = models.DateTimeField(null=True, blank=True)
    action_payload  = models.JSONField(default=dict,
                                       help_text='Machine-readable action details for automation')

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'AI Recommendation'

    def __str__(self):
        return f"[{self.rec_type.upper()}] {self.title}"
