# Generated by Django 6.0.2 on 2026-02-22 11:27

import django.db.models.deletion
import services.container_registry.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_database_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerRepository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('region', models.CharField(choices=[('af-south-1', 'Africa — Johannesburg'), ('eu-west-1', 'Europe — Frankfurt'), ('ap-south-1', 'Asia — Singapore'), ('us-east-1', 'US East — New York'), ('us-west-1', 'US West — Los Angeles')], default='us-east-1', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleting', 'Deleting'), ('error', 'Error')], default='active', max_length=20)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('storage_mb', models.FloatField(default=0.0)),
                ('pull_count', models.PositiveBigIntegerField(default=0)),
                ('push_count', models.PositiveBigIntegerField(default=0)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RegistryToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('token', models.CharField(default=services.container_registry.models.generate_token, max_length=80, unique=True)),
                ('scope', models.CharField(choices=[('pull', 'Pull Only'), ('push', 'Push Only'), ('admin', 'Admin (Push + Pull + Delete)')], default='pull', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_tokens', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='services.containerrepository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_gb', models.FloatField(default=0.0)),
                ('pull_count', models.PositiveIntegerField(default=0)),
                ('push_count', models.PositiveIntegerField(default=0)),
                ('transfer_gb', models.FloatField(default=0.0)),
                ('hourly_cost_usd', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='services.containerrepository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(db_index=True, max_length=128)),
                ('digest', models.CharField(db_index=True, max_length=128)),
                ('size_mb', models.FloatField(default=0.0)),
                ('architecture', models.CharField(default='amd64', max_length=32)),
                ('os', models.CharField(default='linux', max_length=32)),
                ('pushed_by', models.CharField(blank=True, max_length=128)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('vulnerable', 'Vulnerable'), ('error', 'Error')], default='pending', max_length=20)),
                ('vulnerability_count', models.JSONField(default=dict, help_text='{"critical":0,"high":0,"medium":0,"low":0}')),
                ('layer_count', models.PositiveSmallIntegerField(default=0)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.containerrepository')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ReplicationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_region', models.CharField(choices=[('af-south-1', 'Africa — Johannesburg'), ('eu-west-1', 'Europe — Frankfurt'), ('ap-south-1', 'Asia — Singapore'), ('us-east-1', 'US East — New York'), ('us-west-1', 'US West — Los Angeles')], max_length=32)),
                ('target_region', models.CharField(choices=[('af-south-1', 'Africa — Johannesburg'), ('eu-west-1', 'Europe — Frankfurt'), ('ap-south-1', 'Asia — Singapore'), ('us-east-1', 'US East — New York'), ('us-west-1', 'US West — Los Angeles')], max_length=32)),
                ('mode', models.CharField(choices=[('sync', 'Synchronous'), ('async', 'Asynchronous'), ('on_demand', 'On-Demand')], default='async', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_rules', to='services.containerrepository')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'source_region', 'target_region')},
            },
        ),
    ]
