# Generated by Django 6.0.2 on 2026-02-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_container_registry_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='databasebackup',
            name='services_da_databas_7753f1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='databasecredential',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='databasecredential',
            name='database',
        ),
        migrations.RemoveIndex(
            model_name='databasemetric',
            name='services_da_databas_356dd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='manageddatabase',
            name='services_ma_owner_i_bad671_idx',
        ),
        migrations.RemoveIndex(
            model_name='manageddatabase',
            name='services_ma_engine_6a68ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='manageddatabase',
            name='services_ma_region_4121e1_idx',
        ),
        migrations.RemoveField(
            model_name='databasebackup',
            name='database',
        ),
        migrations.DeleteModel(
            name='DatabaseCredential',
        ),
        migrations.RemoveField(
            model_name='databasemetric',
            name='database',
        ),
        migrations.RemoveField(
            model_name='manageddatabase',
            name='owner',
        ),
        migrations.DeleteModel(
            name='DatabaseBackup',
        ),
        migrations.DeleteModel(
            name='DatabaseMetric',
        ),
        migrations.DeleteModel(
            name='ManagedDatabase',
        ),
    ]
