# Generated by Django 6.0.2 on 2026-02-22 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_databasebackup_services_da_databas_7753f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('compute', 'Compute'), ('database', 'Database'), ('storage', 'Storage'), ('networking', 'Networking'), ('containers', 'Containers'), ('email', 'Email'), ('dns', 'DNS'), ('cdn', 'CDN'), ('monitoring', 'Monitoring')], max_length=64, unique=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded Performance'), ('partial_outage', 'Partial Outage'), ('major_outage', 'Major Outage'), ('maintenance', 'Under Maintenance')], default='operational', max_length=32)),
                ('uptime_pct', models.FloatField(default=100.0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'service healths',
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=dict, help_text='Key-value tags for resource')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('service', models.CharField(max_length=64)),
                ('resource_id_filter', models.CharField(blank=True, help_text='Specific resource to watch, or blank for service-wide', max_length=64)),
                ('metric', models.CharField(max_length=64)),
                ('condition', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '==')], default='gt', max_length=8)),
                ('threshold', models.FloatField()),
                ('duration_mins', models.IntegerField(default=5, help_text='Minutes the condition must hold before firing')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('notify_via', models.JSONField(default=list, help_text='List of notification channels')),
                ('notify_target', models.TextField(blank=True, help_text='Email / webhook URL / PagerDuty key')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=dict, help_text='Key-value tags for resource')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('service', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('sev1', 'SEV-1 Critical'), ('sev2', 'SEV-2 High'), ('sev3', 'SEV-3 Medium'), ('sev4', 'SEV-4 Low')], default='sev3', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('postmortem', 'Post-Mortem')], default='open', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('affected_resources', models.JSONField(default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('impact', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='services.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved'), ('silenced', 'Silenced')], default='firing', max_length=16)),
                ('value', models.FloatField(help_text='Metric value that triggered the alert')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='services.alertrule')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='services.monitoringalert'),
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.CharField(db_index=True, max_length=64)),
                ('service', models.CharField(db_index=True, max_length=64)),
                ('metric', models.CharField(choices=[('cpu_percent', 'CPU %'), ('memory_percent', 'Memory %'), ('disk_io_read', 'Disk IO Read (MB/s)'), ('disk_io_write', 'Disk IO Write (MB/s)'), ('network_in', 'Network In (MB/s)'), ('network_out', 'Network Out (MB/s)'), ('latency_ms', 'Latency (ms)'), ('error_rate', 'Error Rate (%)'), ('request_rate', 'Requests/sec'), ('queue_length', 'Queue Length'), ('replication_lag', 'Replication Lag (s)'), ('pod_restarts', 'Pod Restarts'), ('storage_used_pct', 'Storage Used (%)'), ('email_queue', 'Email Queue Length'), ('dns_query_rate', 'DNS Queries/sec')], db_index=True, max_length=64)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['resource_id', 'metric', 'timestamp'], name='services_me_resourc_673c78_idx'), models.Index(fields=['owner', 'service', 'timestamp'], name='services_me_owner_i_7ec3a0_idx')],
            },
        ),
    ]
