# Generated by Django 6.0.2 on 2026-02-22 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicehealth_alertrule_incident_incidentupdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='US', max_length=64)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('credit_balance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('auto_pay', models.BooleanField(default=True)),
                ('spend_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Account',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectable', 'Uncollectable')], default='draft', max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('credits_applied', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reason', models.CharField(choices=[('service_credit', 'Service Credit'), ('promo', 'Promotional Credit'), ('sla', 'SLA Violation'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credits', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to=settings.AUTH_USER_MODEL)),
                ('applied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=14)),
                ('unit', models.CharField(default='unit', max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='services.invoice')),
            ],
            options={
                'ordering': ['service', 'description'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('card', 'Credit / Debit Card'), ('bank_account', 'Bank Account (ACH)'), ('paypal', 'PayPal')], max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('card_brand', models.CharField(blank=True, max_length=32)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.paymentmethod'),
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metric', models.CharField(choices=[('compute_hours', 'Compute Hours'), ('storage_gb', 'Storage GB'), ('bandwidth_gb', 'Bandwidth GB'), ('api_calls', 'API Calls'), ('email_sent', 'Emails Sent'), ('db_hours', 'Database Hours'), ('snapshots', 'Snapshots'), ('ip_addresses', 'Floating IPs'), ('load_balancers', 'Load Balancers')], max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', 'status'], name='services_in_owner_i_1a7dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', 'period_start'], name='services_in_owner_i_dd0be2_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['owner', 'metric', 'period_start'], name='services_us_owner_i_18ee22_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['owner', 'service', 'period_start'], name='services_us_owner_i_f66624_idx'),
        ),
    ]
