# Generated by Django 6.0.2 on 2026-02-25 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_team_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('pipeline_run', 'Pipeline Run'), ('pipeline_failed', 'Pipeline Failed'), ('deployment_started', 'Deployment Started'), ('deployment_succeeded', 'Deployment Succeeded'), ('deployment_failed', 'Deployment Failed'), ('config_changed', 'Config Changed'), ('alert_fired', 'Alert Fired'), ('alert_resolved', 'Alert Resolved'), ('incident_opened', 'Incident Opened'), ('incident_resolved', 'Incident Resolved'), ('kubernetes_sync', 'Kubernetes Sync'), ('user_login', 'User Login'), ('project_created', 'Project Created'), ('security_scan', 'Security Scan')], max_length=32)),
                ('actor', models.CharField(blank=True, max_length=64)),
                ('project_id', models.CharField(blank=True, max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=32)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('resource_name', models.CharField(blank=True, max_length=128)),
                ('environment', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='services_pl_owner_i_d0b626_idx'), models.Index(fields=['owner', 'event_type'], name='services_pl_owner_i_afb5b4_idx'), models.Index(fields=['owner', 'project_id'], name='services_pl_owner_i_202c9c_idx')],
            },
        ),
    ]
