# Generated by Django 6.0.2 on 2026-02-25 20:07

import django.db.models.deletion
import services.apim.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_platformactivityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConsumer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.apim.models._uid_con, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('consumer_type', models.CharField(choices=[('app', 'Application'), ('service', 'Service'), ('team', 'Team'), ('partner', 'Partner'), ('internal', 'Internal')], default='app', max_length=16)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_consumers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_consumers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.apim.models._uid_api, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=16)),
                ('protocol', models.CharField(choices=[('rest', 'REST'), ('graphql', 'GraphQL'), ('grpc', 'gRPC'), ('ws', 'WebSocket')], default='rest', max_length=16)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('apikey', 'API Key'), ('jwt', 'JWT'), ('oauth2', 'OAuth 2.0'), ('mtls', 'mTLS'), ('basic', 'Basic Auth')], default='apikey', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('base_path', models.CharField(blank=True, max_length=255)),
                ('upstream_url', models.CharField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('openapi_spec', models.JSONField(blank=True, default=dict)),
                ('request_count', models.BigIntegerField(default=0)),
                ('error_count', models.BigIntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_apis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_api_definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiGateway',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.apim.models._uid_gw, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('engine', models.CharField(choices=[('kong', 'Kong'), ('envoy', 'Envoy'), ('nginx', 'NGINX'), ('tyk', 'Tyk'), ('orcacloud', 'OrcaCloud Gateway'), ('aws_agw', 'AWS API Gateway')], default='orcacloud', max_length=16)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=16)),
                ('region', models.CharField(default='us-east-1', max_length=64)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('active_apis', models.IntegerField(default=0)),
                ('request_rate', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('latency_p99_ms', models.FloatField(default=0.0)),
                ('uptime_percent', models.FloatField(default=100.0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_gateways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_gateways',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.apim.models._uid_key, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('key_prefix', models.CharField(blank=True, max_length=16)),
                ('key_hash', models.CharField(blank=True, max_length=128)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('rotating', 'Rotating')], default='active', max_length=16)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('rate_limit', models.IntegerField(default=1000)),
                ('quota', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.BigIntegerField(default=0)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='services.apiconsumer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApimAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('api_created', 'API Created'), ('api_updated', 'API Updated'), ('api_deprecated', 'API Deprecated'), ('api_deleted', 'API Deleted'), ('gateway_registered', 'Gateway Registered'), ('gateway_updated', 'Gateway Updated'), ('consumer_created', 'Consumer Created'), ('key_generated', 'Key Generated'), ('key_revoked', 'Key Revoked'), ('key_rotated', 'Key Rotated'), ('policy_attached', 'Policy Attached'), ('policy_detached', 'Policy Detached'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated')], max_length=32)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.CharField(blank=True, max_length=40)),
                ('entity_name', models.CharField(blank=True, max_length=150)),
                ('environment', models.CharField(blank=True, max_length=16)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApimMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('api', 'API'), ('gateway', 'Gateway')], max_length=16)),
                ('resource_id', models.CharField(max_length=40)),
                ('metric_type', models.CharField(choices=[('request_rate', 'Request Rate (req/s)'), ('error_rate', 'Error Rate (%)'), ('latency_p50', 'Latency P50 (ms)'), ('latency_p95', 'Latency P95 (ms)'), ('latency_p99', 'Latency P99 (ms)'), ('bandwidth_in', 'Bandwidth In (bytes/s)'), ('bandwidth_out', 'Bandwidth Out (bytes/s)'), ('status_2xx', 'HTTP 2xx Count'), ('status_4xx', 'HTTP 4xx Count'), ('status_5xx', 'HTTP 5xx Count')], max_length=20)),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_metric_snapshots',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.apim.models._uid_pol, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('policy_type', models.CharField(choices=[('rate_limit', 'Rate Limiting'), ('auth', 'Authentication'), ('cors', 'CORS'), ('transform', 'Transformation'), ('cache', 'Caching'), ('ip_filter', 'IP Filtering'), ('circuit_break', 'Circuit Breaker'), ('retry', 'Retry'), ('logging', 'Logging'), ('custom', 'Custom')], default='rate_limit', max_length=20)),
                ('scope', models.CharField(choices=[('gateway', 'Gateway'), ('api', 'API'), ('product', 'Product')], default='api', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_policies',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiPolicyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_attachments', to='services.apidefinition')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_attachments', to='services.apigateway')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.apipolicy')),
            ],
            options={
                'db_table': 'apim_policy_attachments',
            },
        ),
        migrations.CreateModel(
            name='ApiProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.apim.models._uid_prod, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], default='free', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=16)),
                ('rate_limit', models.IntegerField(default=1000)),
                ('quota', models.IntegerField(default=0)),
                ('burst_limit', models.IntegerField(default=200)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apim_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apim_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiProductApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.apidefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.apiproduct')),
            ],
            options={
                'db_table': 'apim_product_apis',
            },
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='apis',
            field=models.ManyToManyField(blank=True, related_name='products', through='services.ApiProductApi', to='services.apidefinition'),
        ),
        migrations.CreateModel(
            name='GatewayApiRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_routes', to='services.apidefinition')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='services.apigateway')),
            ],
            options={
                'db_table': 'apim_gateway_api_routes',
            },
        ),
        migrations.AddIndex(
            model_name='apiconsumer',
            index=models.Index(fields=['owner', 'environment', 'active'], name='apim_consum_owner_i_71ad2f_idx'),
        ),
        migrations.AddIndex(
            model_name='apidefinition',
            index=models.Index(fields=['owner', 'environment'], name='apim_api_de_owner_i_1cd8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='apidefinition',
            index=models.Index(fields=['owner', 'status'], name='apim_api_de_owner_i_acd95a_idx'),
        ),
        migrations.AddIndex(
            model_name='apigateway',
            index=models.Index(fields=['owner', 'environment', 'health'], name='apim_gatewa_owner_i_eb1397_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['consumer', 'status'], name='apim_api_ke_consume_c49a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['owner', 'environment', 'status'], name='apim_api_ke_owner_i_91177a_idx'),
        ),
        migrations.AddIndex(
            model_name='apimauditlog',
            index=models.Index(fields=['owner', '-created_at'], name='apim_audit__owner_i_0c31a6_idx'),
        ),
        migrations.AddIndex(
            model_name='apimauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='apim_audit__entity__23fa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='apimmetricsnapshot',
            index=models.Index(fields=['resource_id', 'metric_type', '-recorded_at'], name='apim_metric_resourc_9ba318_idx'),
        ),
        migrations.AddIndex(
            model_name='apimmetricsnapshot',
            index=models.Index(fields=['owner', '-recorded_at'], name='apim_metric_owner_i_b2ffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='apipolicy',
            index=models.Index(fields=['owner', 'policy_type', 'enabled'], name='apim_polici_owner_i_4e6244_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apiproductapi',
            unique_together={('product', 'api')},
        ),
        migrations.AlterUniqueTogether(
            name='gatewayapiroute',
            unique_together={('gateway', 'api')},
        ),
    ]
