# Generated by Django 6.0.2 on 2026-02-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_apiconsumer_apidefinition_apigateway_apikey_and_more'),
    ]

    operations = []
