# Generated by Django 6.0.2 on 2026-03-01 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_accesskey_ddosprotectionrule_ddosattackevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMeshPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=dict, help_text='Key-value tags for resource')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('policy_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cluster_id', models.CharField(blank=True, help_text='KubernetesCluster.cluster_id (blank = VPC-wide)', max_length=64)),
                ('namespace', models.CharField(blank=True, help_text='K8s namespace selector (empty = all namespaces)', max_length=128)),
                ('workload_selector', models.JSONField(default=dict, help_text='Label selector dict, e.g. {"app": "api"}')),
                ('mtls_mode', models.CharField(choices=[('strict', 'Strict — all traffic must use mTLS'), ('permissive', 'Permissive — accept both plain-text and mTLS'), ('disabled', 'Disabled — no mTLS enforcement')], default='permissive', max_length=12)),
                ('proxy_type', models.CharField(choices=[('envoy', 'Envoy'), ('linkerd', 'Linkerd'), ('none', 'No sidecar')], default='envoy', max_length=10)),
                ('allowed_sources', models.JSONField(default=list, help_text='Allowed source identifiers (CIDR, selectors, or "*")')),
                ('egress_allowed', models.BooleanField(default=True)),
                ('egress_allowlist', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('vpc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesh_policies', to='services.vpc')),
            ],
            options={
                'verbose_name': 'Service Mesh Policy',
                'ordering': ['-created_at'],
            },
        ),
    ]
