# Generated by Django 6.0.2 on 2026-03-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_webhook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
