# Generated by Django 6.0.2 on 2026-03-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_operational_component_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='runningprocess',
            new_name='services_ru_owner_i_1e2394_idx',
            old_name='running_owner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='runningprocess',
            new_name='services_ru_process_405456_idx',
            old_name='running_type_status_idx',
        ),
        migrations.AddField(
            model_name='runningprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='componentstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='componentstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Extra metadata (branch, commit, etc.)'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='progress_pct',
            field=models.IntegerField(default=0, help_text='0-100'),
        ),
        migrations.AlterField(
            model_name='runningprocess',
            name='resource_ref',
            field=models.CharField(blank=True, help_text='Human-readable resource name or path', max_length=255),
        ),
    ]
