# Generated by Django 6.0.2 on 2026-03-04 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_group_groups_grou_owner_i_17469e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(db_index=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('metric', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['owner', 'service', 'event_time'], name='services_pl_owner_i_fe2f80_idx'), models.Index(fields=['processed', 'event_time'], name='services_pl_process_163263_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBillingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('service', models.CharField(db_index=True, max_length=64)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_units', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('record_count', models.IntegerField(default=0)),
                ('is_mock', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'service'],
                'indexes': [models.Index(fields=['owner', 'year', 'week_number'], name='services_we_owner_i_8a3d5c_idx'), models.Index(fields=['owner', 'week_start'], name='services_we_owner_i_e566cc_idx')],
                'unique_together': {('owner', 'week_start', 'service')},
            },
        ),
    ]
