# Generated by Django 6.0.2 on 2026-03-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_organization_contact_email_organization_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='department_lead',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='services.department'),
        ),
    ]
