# Generated by Django 6.0.2 on 2026-03-04 08:39

import django.db.models.deletion
import services.marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_dept_category_lead_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingWorkspaceSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('default_from_name', models.CharField(blank=True, max_length=100)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('default_reply_to', models.EmailField(blank=True, max_length=254)),
                ('brand_color', models.CharField(blank=True, max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('unsubscribe_page', models.URLField(blank=True)),
                ('gdpr_enabled', models.BooleanField(default=True)),
                ('popia_enabled', models.BooleanField(default=False)),
                ('api_keys', models.JSONField(default=dict)),
                ('permissions', models.JSONField(default=dict, help_text='Role → permission mapping')),
            ],
            options={
                'verbose_name': 'Marketing Workspace Settings',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.marketing.models._seg_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('organization', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('segment_type', models.CharField(choices=[('dynamic', 'Dynamic'), ('static', 'Static')], default='static', max_length=10)),
                ('criteria', models.JSONField(default=dict, help_text='Filter rules: [{field, operator, value}]')),
                ('contact_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Segment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='automation',
            name='organization',
            field=models.CharField(blank=True, db_index=True, help_text='Enterprise org ID (optional org scope)', max_length=36),
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('social', 'Social'), ('push', 'Push Notification'), ('multi', 'Multi-Channel'), ('ads', 'Ads')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='objective',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.CharField(blank=True, db_index=True, help_text='Enterprise org ID (optional org scope)', max_length=36),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='organization',
            field=models.CharField(blank=True, db_index=True, help_text='Enterprise org ID (optional org scope)', max_length=36),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='organization',
            field=models.CharField(blank=True, db_index=True, help_text='Enterprise org ID (optional org scope)', max_length=36),
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.marketing.models._abt_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('organization', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('hypothesis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('test_type', models.CharField(choices=[('subject', 'Subject Line'), ('creative', 'Creative'), ('audience', 'Audience'), ('send_time', 'Send Time'), ('cta', 'Call to Action')], default='subject', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('winner_variant', models.CharField(blank=True, max_length=36)),
                ('auto_select_winner', models.BooleanField(default=True)),
                ('winner_metric', models.CharField(default='open_rate', help_text='open_rate | click_rate | conversion_rate', max_length=20)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests', to='services.campaign')),
            ],
            options={
                'verbose_name': 'AB Test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABTestVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.marketing.models._var_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='A, B, C …', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('subject_line', models.CharField(blank=True, max_length=255)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('allocation', models.FloatField(default=0.5, help_text='Traffic share 0.0–1.0')),
                ('sends', models.PositiveIntegerField(default=0)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('ab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.abtest')),
            ],
            options={
                'verbose_name': 'AB Test Variant',
                'ordering': ['ab_test', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.marketing.models._cal_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('organization', models.CharField(db_index=True, max_length=36)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('campaign', 'Campaign'), ('automation', 'Automation'), ('post', 'Social Post'), ('deadline', 'Deadline'), ('other', 'Other')], default='other', max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, help_text='hex color for UI', max_length=20)),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='services.campaign')),
            ],
            options={
                'verbose_name': 'Marketing Calendar Event',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.marketing.models._chn_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('organization', models.CharField(db_index=True, max_length=36)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('social', 'Social'), ('push', 'Push Notification'), ('ads', 'Ads')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('unconfigured', 'Unconfigured'), ('disconnected', 'Disconnected')], default='unconfigured', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='e.g. SendGrid, Twilio, Facebook', max_length=100)),
                ('config', models.JSONField(default=dict, help_text='Provider-specific config (API keys, etc.)')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marketing Channel',
                'ordering': ['organization', 'channel_type'],
                'unique_together': {('organization', 'channel_type', 'name')},
            },
        ),
    ]
