# Generated by Django 6.0.2 on 2026-03-04 14:25

import django.db.models.deletion
import services.enterprise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_marketing_workspace_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSidebarItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=services.enterprise.models._dsbi_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('navigation', 'Navigation'), ('action', 'Quick Action'), ('resource', 'Resource'), ('highlight', 'Highlight'), ('custom', 'Custom Link')], default='navigation', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_items', to='services.department')),
            ],
            options={
                'verbose_name': 'Department Sidebar Item',
                'ordering': ['item_type', 'order_index'],
            },
        ),
    ]
