# Generated by Django 6.0.2 on 2026-03-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_department_sidebar_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain_email',
            field=models.CharField(blank=True, default='', help_text='Email domain used by org members, e.g. acme.com', max_length=253),
        ),
    ]
