# Generated by Django 6.0.2 on 2026-03-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_add_domain_email_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='domain_email',
            field=models.EmailField(blank=True, default='', help_text='Primary organization email, e.g. admin@acme.com', max_length=254),
        ),
    ]
