# Generated by Django 6.0.7 on 2026-07-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_change_domain_email_to_emailfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandAsset',
        ),
        migrations.DeleteModel(
            name='BrandingProfile',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentSidebarItem',
        ),
        migrations.DeleteModel(
            name='EmailSenderIdentity',
        ),
        migrations.DeleteModel(
            name='EnterpriseEmailTemplate',
        ),
        migrations.DeleteModel(
            name='EnterpriseInvoice',
        ),
        migrations.DeleteModel(
            name='EnterprisePlan',
        ),
        migrations.DeleteModel(
            name='EnterpriseSendDomain',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='OrgDomain',
        ),
        migrations.DeleteModel(
            name='OrgDomainRecord',
        ),
        migrations.DeleteModel(
            name='OrgGroup',
        ),
        migrations.DeleteModel(
            name='OrgTeam',
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
        migrations.DeleteModel(
            name='EnterpriseAuditLog',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
