# Generated by OrcaCloud — initial catalog migration

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalogEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cloud_type",
                    models.CharField(
                        choices=[
                            ("public",  "Public Cloud"),
                            ("private", "Private Cloud"),
                            ("hybrid",  "Hybrid Cloud"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("service_slug",      models.CharField(db_index=True, max_length=64)),
                ("display_name",      models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("compute",       "Compute"),
                            ("storage",       "Storage"),
                            ("networking",    "Networking"),
                            ("identity",      "Identity & Access"),
                            ("orchestration", "Orchestration"),
                            ("security",      "Security"),
                            ("monitoring",    "Monitoring & Telemetry"),
                            ("dns",           "DNS & Load Balancing"),
                            ("object",        "Object Storage"),
                            ("database",      "Database"),
                            ("container",     "Container / Kubernetes"),
                        ],
                        default="compute",
                        max_length=32,
                    ),
                ),
                ("openstack_service", models.CharField(blank=True, max_length=64)),
                ("description",       models.TextField(blank=True)),
                ("is_enabled",        models.BooleanField(db_index=True, default=True)),
                ("is_preview",        models.BooleanField(default=False)),
                ("is_billable",       models.BooleanField(default=True)),
                ("icon_url",          models.URLField(blank=True)),
                ("docs_url",          models.URLField(blank=True)),
                ("constraints",       models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name":        "Service Catalog Entry",
                "verbose_name_plural": "Service Catalog Entries",
                "ordering":            ["cloud_type", "category", "service_slug"],
            },
        ),
        migrations.AddConstraint(
            model_name="servicecatalogentry",
            constraint=models.UniqueConstraint(
                fields=["cloud_type", "service_slug"],
                name="unique_cloud_type_service_slug",
            ),
        ),
        migrations.CreateModel(
            name="ServiceCatalogPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_policies",
                        to="workspace.workspace",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_policies",
                        to="catalog.servicecatalogentry",
                    ),
                ),
                ("is_allowed", models.BooleanField(default=True)),
                ("reason",     models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name":        "Service Catalog Policy",
                "verbose_name_plural": "Service Catalog Policies",
                "ordering":            ["workspace", "entry"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="servicecatalogpolicy",
            unique_together={("workspace", "entry")},
        ),
    ]
