# Generated by Django 6.0.2 on 2026-03-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecatalogpolicy',
            options={'ordering': ['workspace', 'entry'], 'verbose_name': 'Service Catalog Policy'},
        ),
        migrations.RemoveConstraint(
            model_name='servicecatalogentry',
            name='unique_cloud_type_service_slug',
        ),
        migrations.AlterField(
            model_name='servicecatalogentry',
            name='constraints',
            field=models.JSONField(blank=True, default=dict, help_text='Optional limits/defaults, e.g. {"max_vcpus": 256, "allowed_regions": ["RegionA"]}'),
        ),
        migrations.AlterField(
            model_name='servicecatalogentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicecatalogentry',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Feature-flagged / beta service'),
        ),
        migrations.AlterField(
            model_name='servicecatalogentry',
            name='openstack_service',
            field=models.CharField(blank=True, help_text='Underlying OpenStack project name (nova, neutron, …)', max_length=64),
        ),
        migrations.AlterField(
            model_name='servicecatalogentry',
            name='service_slug',
            field=models.CharField(db_index=True, help_text='Short machine-readable key, e.g. nova, cinder, barbican', max_length=64),
        ),
        migrations.AlterField(
            model_name='servicecatalogpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='servicecatalogentry',
            unique_together={('cloud_type', 'service_slug')},
        ),
    ]
