apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - orcacloud-postgres.yaml
  - fast-ssd-postgres-pv.yaml
  - orcacloud-redis.yaml
  - orcacloud-backend.yaml
  - orcacloud-frontend.yaml
  - orcacloud-celery.yaml
  - orcacloud-ingress.yaml
