apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orcacloud-tls-staging
  namespace: orcacloud
spec:
  secretName: orcacloud-tls-staging
  dnsNames:
  - orcacloud.com
  - www.orcacloud.com
  - api.orcacloud.com
  issuerRef:
    name: letsencrypt-staging-dns-cloudflare
    kind: ClusterIssuer
