apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - local-pvs.yaml

patches:
  - path: patch-backend-image.yaml
  - path: patch-backend-init-image.yaml
  - path: patch-frontend-image.yaml
  - path: patch-celery-image.yaml
  - path: ingress-patch.yaml
  - path: toleration-backend.yaml
  - path: toleration-frontend.yaml
  - path: toleration-postgres.yaml
  - path: toleration-redis.yaml
  - path: toleration-celery.yaml
  - path: toleration-flower.yaml
