apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: orcacloud
spec:
  template:
    spec:
      initContainers:
      - name: migrate
        image: atonixdev/orcacloud-backend:1.0.1
