apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: orcacloud
spec:
  template:
    spec:
      containers:
      - name: celery-worker
        image: orcacloud/orcacloud-backend:1.0.1
