apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: orcacloud
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: atonixdev/orcacloud-frontend:1.0.0
